### ISSUE TITLE
the tool not show when offline

### ISSUE THREAD

**Issue by jesse996** [forge42dev/Remix-Dev-Tools#119]

**Comment by AlemTuzlak** [comment]
what do you mean exactly by "offline"?

**Comment by jesse996** [comment]
> what do you mean exactly by "offline"?

I mean the network .
it only show when the network is on

**Comment by AlemTuzlak** [comment]
@jesse996 that is actually correct, the tool communicates with itself by sending requests to URL: "remix-development-tools-request" so that might be the issue, if you whitelist it you should be good to go

**Comment by AlemTuzlak** [comment]
if this doesn't help feel free to let me know, will close for now, the tool doesn't support full offline-mode officially so this isn't really a bug but rather lack of support

**Comment by jesse996** [comment]
> if this doesn't help feel free to let me know, will close for now, the tool doesn't support full offline-mode officially so this isn't really a bug but rather lack of support

will it support offline-mode in the future?
