### ISSUE TITLE
Upgrading to 4.1.0 console issue

### ISSUE THREAD

**Issue by nicksrandall** [forge42dev/Remix-Dev-Tools#120]
In every `.server` file where I reference a `console` method inside a callback, vite can no long transpile that module and I instead get an error saying: `ERROR: Expected ")" but found ";"`

Example broken page:

```
// redis.server.ts
export const redis = new Redis(REDIS_URL, {
    commandTimeout: 5000,
    enableAutoPipelining: true,
    maxRetriesPerRequest: 3,
  });
  redis.on("connect", () => console.debug("Redis connected"));
  redis.on("close", () => console.debug("Redis connection closed"));
  redis.on("reconnecting", () => console.log("Redis reconnecting"));
  redis.removeAllListeners("error");
  redis.on("error", (error: Error) => console.error("Redis error", error));
```

**Comment by nicksrandall** [comment]
After a little more debugging, I actually think the ".server" thing might not be the cause. I'm also seeing the bug on a "route" file.

**Comment by AlemTuzlak** [comment]
@nicksrandall can you try with 4.1.1

**Comment by nicksrandall** [comment]
@AlemTuzlak I have less errors but the app will still not compile with 4.1.1.

Here is another example of an failing page.

```ts
import { Analytics } from "@segment/analytics-node";

export const analytics = new Analytics({
  writeKey: "fake",
  maxEventsInBatch: 1,
}).on("error", console.error);
```

**Comment by nicksrandall** [comment]
I also think it might be finding some code in this text that I inline?

```
function renderSegmentSnippet() {
  return `!function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware"];analytics.factory=function(e){return function(){if(window.analytics.initialized)return window.analytics[e].apply(window.analytics,arguments);var i=Array.prototype.slice.call(arguments);i.unshift(e);analytics.push(i);return analytics}};for(var i=0;i<analytics.methods.length;i++){var key=analytics.methods[i];analytics[key]=analytics.factory(key)}analytics.load=function(key,i){var t=document.createElement("script");t.type="text/javascript";t.async=!0;t.src="https://cdn.segment.com/analytics.js/v1/" + key + "/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n);analytics._loadOptions=i};analytics._writeKey="fake";;analytics.SNIPPET_VERSION="4.16.1";
analytics.load("fake");
}}();`;
}
```

**Comment by houmark** [comment]
Same for me. My app completely broke after updating to 4.1.1. Errors refer to code that either don't exist or is out-commented. My app is using Cloudflare. @AlemTuzlak happy to help debugging in chat, just ping me :)

**Comment by actraiser** [comment]
just to add into the feedback, when upgrading to 4.1.1 Remix Run Devmode is not working anymore : 

```
07:04:50 [vite] Pre-transform error: Transform failed with 1 error:
/some/perfectly/fine/file.ts: ERROR: Expected "}" but found ";"
```

App builds and runs fine for production or when I disable Remix Dev Tools in Development.

Greets
-act

**Comment by AlemTuzlak** [comment]
@actraiser @nicksrandall mind trying now? v4.1.3, I think it should be okay now, if not could you post the examples of failing code snippets!

**Comment by actraiser** [comment]
Unfortunately still the same error for me with remix-development-tools 4.1.3

**Comment by AlemTuzlak** [comment]
I've hidden the feature behind an opt-in flag called `unstable_console` I'll try to fix up the issues but it would be appreciated if you guys provided code snippets so that I know what causes it!

**Comment by actraiser** [comment]
Since upgrading to 4.1.4, everything works as expected again on my end.

Greets
-act

**Comment by nilsbunger** [comment]
I had a related error using v4.1.0: 

A commented out console.log command, eg 

// console.log("Hello")

in entry.server.tsx's handleRequest() will log to console.

Upgrading to 4.1.4 fixes this for me. 

I'm making a comment rather than a new issue as these are probably the same problem, and since I no longer have the problem with 4.1.4.

**Comment by AlemTuzlak** [comment]
@nilsbunger it was actually hidden behind `unstable_console` and when you set that to true you should be able to see if it's still an issue or not, but I'm pretty certain that specific scenario should be fixed with the latest version
