### ISSUE TITLE
Matching routes hierarchy with remix-flat-routes

### ISSUE THREAD

**Issue by martialanouman** [forge42dev/Remix-Dev-Tools#122]
I got a Remix app with remix-flat-routes configured.
Currently when we open `routes` section inside RDT, the routes hierarchy graph does not reflect the actual routes hierarchy.

![image](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/80514220/e8123957-2195-49ab-922c-d67bf640d083)

As you can see, colocated files are shown as routes while there're not.

**Comment by DavidGutierrez94** [comment]
I have the same issue

**Comment by AlemTuzlak** [comment]
I'll see if I can get this added in

**Comment by kiliman** [comment]
Can you show me your remix config?

**Comment by martialanouman** [comment]
Hi @kiliman ,
Sorry for the delay. Here is my remix config:

```typescript
import type { VitePluginConfig } from '@remix-run/dev'
import { flatRoutes } from 'remix-flat-routes'

export default {
	routes: async defineRoutes => flatRoutes('routes', defineRoutes),
} satisfies VitePluginConfig

```

Current Remix version: 2.8.1

**Comment by kiliman** [comment]
Ok, I see the issue. You're not ignoring the default routing convention, so you have a mix of standard v2 routing _plus_ remix flat routes.

Update your config to:
```ts
import type { VitePluginConfig } from '@remix-run/dev'
import { flatRoutes } from 'remix-flat-routes'

export default {
	ignoredRouteFiles: ['**/*'], // ignore all existing routes from default convention    
	routes: async defineRoutes => flatRoutes('routes', defineRoutes),
} satisfies VitePluginConfig
```

**Comment by martialanouman** [comment]
Oh... i missed that. Thanks @kiliman
