### ISSUE TITLE
mouseenter event listener prevent other mouseenter events from firing

### ISSUE THREAD

**Issue by yoni-noma** [forge42dev/Remix-Dev-Tools#124]
So im using ag-grid Table component and i noticed that my row hlghight on hover doesnt work.
after debugging the system ive noticed in the chrome devtools that there is a mouseenter event listener of remix-development-tools  on the Documen object. if i remove it everything start to work again.

attaching a screenshot of the event from the devtools, you can see there as well another listener of the table(which never fires unless i removed the remix-development-tools one.):
<img width="1016" alt="Screenshot 2024-04-15 at 17 11 05" src="https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/159265988/af4edb3b-72ce-43f8-ab6a-874aeead4811">

**Comment by AlemTuzlak** [comment]
Interesting, this should be a pretty simple fix, I'll take care of it soon!
