### ISSUE TITLE
Version 4.1.5 isnt published to npm

### ISSUE THREAD

**Issue by yoni-noma** [forge42dev/Remix-Dev-Tools#127]
For some reason i cant install version 4.1.5, i can see the tag in this repository but npm shows only 4.1.4.

https://www.npmjs.com/package/remix-development-tools

![Screenshot 2024-05-05 at 11 22 11](https://github.com/forge42dev/Remix-Dev-Tools/assets/159265988/ab18fa37-109c-4ab0-92dd-a2e2c5cc3307)

**Comment by AlemTuzlak** [comment]
@yoni-noma whoops sorry about that, should be available now
