### ISSUE TITLE
Keyboard shortcut open/close

### ISSUE THREAD

**Issue by Doddle-BE** [forge42dev/Remix-Dev-Tools#129]
The keyboard shortcut to open/close the tool has been chosen too generally. The uppercase 'A' is a fairly common choice for the start of a sentence or proper nouns.

Perhaps adding the ability to change the shortcut would not be a bad feature. But a combination of three keys would also be a great help.

**Comment by AlemTuzlak** [comment]
@Doddle-BE you're absolutely correct, I've been meaning to fix this for a while now I'm just thinking if it should be configurable or something very specific.

**Comment by Doddle-BE** [comment]
@AlemTuzlak thanks for the answer.

I've changed the shortcut to Ctrl + Shift + A. Works for me.
But I'm really convinced you should give your users the possibility to customise this.

**Comment by AlemTuzlak** [comment]
Configurable from 4.2.0
