### ISSUE TITLE
No trigger element is showing (not in the DOM)

### ISSUE THREAD

**Issue by ilikebuttons** [forge42dev/Remix-Dev-Tools#131]
1.  ran `npm install remix-development-tools -D`

**package.json**
```
"devDependencies": {
    "remix-development-tools": "^4.1.6",
}
```
2.  added config
**vite.config.js**
```
import { vitePlugin as remix } from "@remix-run/dev";
import { installGlobals } from "@remix-run/node";
import { defineConfig } from "vite";
import { remixDevTools } from "remix-development-tools";
import tsconfigPaths from "vite-tsconfig-paths";

installGlobals();

export default defineConfig({
    ssr: {
        noExternal: ['use-sound']
    },
    plugins: [
        remixDevTools(),
        remix({
            ignoredRouteFiles: ["**/*.css"]
        }),
        tsconfigPaths()
    ]
});
```
3.  ran `npm run dev`

No trigger element on the page (also looked in the DOM in case it was hidden or off-screen), however the log messages do appear in the terminal-
```
[1] LOADER root triggered - 0.4 ms
[1] LOADER routes/squad._index triggered - 0.31 ms
[1] LOADER routes/squad.$id triggered - 0.49 ms
[1] LOADER routes/squad.$id.loadout.$loId triggered - 0.29 ms
```

Using Chrome version 124, also tried incognito mode and Firefox, and pressing Shift + A to open dev tools.
The `<Scripts/>` component is in `<body>` of **root.jsx** and JS is enabled in browser.
Tried with and without a custom config.

**Comment by ilikebuttons** [comment]
Hi Alem, thanks for the quick reply. I was getting a hydration error in root.jsx when starting the dev server. I thought it was because I was wrapping everything in a Context.Provider for sound effects. I created a wrapper for <main> and put it in there but the error is still present-
```
Warning: Extra attributes from the server: class
    at html
    at App
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/@remix-run_react.js?v=6aae04e8:857:5)
    at RenderErrorBoundary (http://localhost:5173/node_modules/.vite/deps/@remix-run_react.js?v=6aae04e8:817:5)
    at DataRoutes (http://localhost:5173/node_modules/.vite/deps/@remix-run_react.js?v=6aae04e8:2039:5)
    at Router (http://localhost:5173/node_modules/.vite/deps/@remix-run_react.js?v=6aae04e8:1198:15)
    at RouterProvider (http://localhost:5173/node_modules/.vite/deps/@remix-run_react.js?v=6aae04e8:1856:5)
    at RemixErrorBoundary (http://localhost:5173/node_modules/.vite/deps/@remix-run_react.js?v=6aae04e8:6599:5)
    at RemixBrowser (http://localhost:5173/node_modules/.vite/deps/@remix-run_react.js?v=6aae04e8:7437:46)
```
I had seen something similar before and it turned out to be the Dark Reader chrome extension, so I disabled it on localhost URLs. It might be some other extension because if I use incognito mode I don't see the error, but I still don't see the trigger element.

**Comment by ilikebuttons** [comment]
I’ve done some further investigation into the issue and found a way to consistently replicate the problem.

### Steps to Reproduce

1. Start a new Remix project using:
   ```
   npx create-remix@latest
   ```
2. Follow the instructions in the README to add Remix Development Tools (RDT) to the project.
3. Change the `root.tsx` file to `root.jsx`.

### Findings

It appears that RDT does not support JavaScript (`.jsx`) even though TypeScript is not a requirement for a Remix project. This limitation is not mentioned in the README or on the [Remix Development Tools site](https://remix-development-tools.fly.dev/).

### Expected Behavior

RDT should support both JavaScript and TypeScript, as Remix projects can be developed in either language.

### Suggested Improvements

1. **Add JavaScript Support:** Ensure that RDT works with JavaScript files (`.jsx`) as well as TypeScript files (`.tsx`).
2. **Update Documentation:** Clearly state in the README and on the website that RDT currently only supports TypeScript if that is indeed the case. This will help set correct expectations for developers who are using JavaScript.

Please let me know if there are any workarounds or if you need any further information from my end.

**Comment by AlemTuzlak** [comment]
Omg I didn't see the extension in your original reply, okay I'll fix this, ahould be pretty easy fix

**Comment by AlemTuzlak** [comment]
Fixed
