### ISSUE TITLE
Server crash when exception thrown during deferred data

### ISSUE THREAD

**Issue by jrestall-finact** [forge42dev/Remix-Dev-Tools#134]
Dev Tools seems to override the resolving of deferred values but there's no exception handler so any exception bubbles up and crashes the server. Without the RDT plugin, the exception is handled as expected.

https://github.com/forge42dev/Remix-Dev-Tools/blob/3bdceb88fe43660f0491967177df1d841a061ead/src/server/utils.ts#L91-L95

Can be reproduced with:

```tsx
export async function loader({ context }: LoaderFunctionArgs) {
  const error = async () => {
    throw new Error("Crash!");
  };

  return defer({
    a: error(),
  });
}
``` 

Likely fixed with:

```ts
    response.deferredKeys.map((key: string) => {
      response.data[key].then(() => {
        const end = diffInMs(start);
        infoLog(`Deferred value ${chalk.white(key)} resolved in ${chalk.blueBright(id)} - ${chalk.white(`${end}ms`)}`);
      }).catch(() => {});
```

**Comment by AlemTuzlak** [comment]
Thank you, I'm pretty sure that's the fix, will publish soon !

**Comment by AlemTuzlak** [comment]
@jrestall-finact Added the fix, plus added error logs on top so you know why it crashed :), thank you for the help, even though you're not using your usual github acc 😆

**Comment by jrestall** [comment]
> @jrestall-finact Added the fix, plus added error logs on top so you know why it crashed :), thank you for the help, even though you're not using your usual github acc 😆

Thanks so much @AlemTuzlak! Appreciate the quick fix and all the work you do on Remix! Forgot to switch from my work account lol.

**Comment by AlemTuzlak** [comment]
Thanks mate, really appreciated! Hehe I know you by name so no worries!
