### ISSUE TITLE
server.silent config isn't working

### ISSUE THREAD

**Issue by derekr** [forge42dev/Remix-Dev-Tools#140]
Tried setting silent, but I still see remix dev tools server logs. On `4.2.3`. 

Also tried with the `server.logs` config and logs still show up in console.

![image](https://github.com/user-attachments/assets/bc01ea25-6078-419e-bfad-d3c8bfd1b260)

**Comment by AlemTuzlak** [comment]
@derekr please try now with https://github.com/forge42dev/Remix-Dev-Tools/releases/tag/v4.3.2

**Comment by derekr** [comment]
Looks good! Thanks @AlemTuzlak!
