### ISSUE TITLE
click to open path in "Errors" section is missing file-extension in pathname

### ISSUE THREAD

**Issue by mtin79** [forge42dev/Remix-Dev-Tools#157]
hi there,
i got an issue when i click a path of a file that is showing up in the errors section of remix dev tools.

e.g.:
when i click the following pathname:
```
label element can't be nested inside of a element
The parent element is located inside of the
/Users/mtin79/Development/Repositories/datenmassiv/sgp-webapp/app/components/ServicesRelevant.tsx
```
<img width="869" alt="Screenshot 2024-10-28 at 09 57 04" src="https://github.com/user-attachments/assets/7f1686f8-5563-4102-855a-1c43f216781e">

the path that is sent do my editor is, and therefore opens a new empty file:
```path:  .../app/components/ServicesRelevant```
<img width="177" alt="Screenshot 2024-10-28 at 09 57 12" src="https://github.com/user-attachments/assets/c779d2b6-3cf1-4b72-82bb-5cc6a0337bad">

so the file extensions is truncated.
propably here?
<img width="786" alt="Screenshot 2024-10-28 at 09 57 43" src="https://github.com/user-attachments/assets/49645264-1d2e-4e80-9a17-bbb9659f6c22">

thanks for help!

**Comment by AlemTuzlak** [comment]
should work in 4.7.6 @mtin79
