### ISSUE TITLE
Pollution of browser console logs

### ISSUE THREAD

**Issue by paul-vd** [forge42dev/Remix-Dev-Tools#158]
During development the console logs are spammed with `res` values due to this console log: https://github.com/forge42dev/Remix-Dev-Tools/blob/66d252e83cd66738b9ee2ab9123fd16911caa42f/src/client/components/jsonRenderer.tsx#L33

I patched it to remove that, but it would be great if this could be configured in the `client` options.

```diff
diff --git a/dist/client.js b/dist/client.js
index 6bdc7f3a7c642679d6a13b0d6b62d49d4a09e8a9..c1108e51664da96bb781084f8fc77160bfb651e5 100644
--- a/dist/client.js
+++ b/dist/client.js
@@ -3446,7 +3446,8 @@ var JsonRenderer = ({ data }) => {
         value.then((res) => {
           if (!ref.current)
             return;
-          console.log(res);
+          // see https://github.com/forge42dev/Remix-Dev-Tools/issues/158
+          // console.log(res);
           setJson((json2) => ({
             ...json2,
             [key]: res
```

**Comment by AlemTuzlak** [comment]
Oh wow this is not supposed to be configured but removed,  I'll release a patch release today!

**Comment by paul-vd** [comment]
![4777431](https://github.com/user-attachments/assets/a6f318c6-885b-4168-ae58-e870baa12727)

Thanks @AlemTuzlak
