### ISSUE TITLE
clicking on app/routes/foo.bar.baz.$bazId.tsx in error tab opens vscode file `baz..tsx`

### ISSUE THREAD

**Issue by Jacubeit** [forge42dev/Remix-Dev-Tools#94]
When clicking in the error pane on a route file that has dot delimiters it does not open the desired file.
Instead it seems it opens the part before the `$` and then uses two dots.

```txt
remix 2.5.0
"remix-development-tools": "^3.7.2"
VSCode: Version: 1.85.1
Mac Sonoma 14.2.1
```

**Comment by AlemTuzlak** [comment]
@Jacubeit There seems to be some sort of issue with react dev tools debug source but I'm not sure if it's OS related or not because I haven't seen this on Windows and I don't own a mac, would you mind opening up your chrome dev tools and seeing whats data-rdt-source set to?

**Comment by Jacubeit** [comment]
@AlemTuzlak what we could do is a quick zoom/hangout and a screen share?
That would most probably give you a quick way of searching around?

**Comment by AlemTuzlak** [comment]
@Jacubeit I think I tracked down the issue and fixed it, mind trying it out on v4
